package com.example.demo;

import lombok.Data;

@Data
public class Event {
    private String id;
    private String type;
    private String source;
    private String data;
    private String time;

    // Constructors, getters, and setters can be generated by Lombok
}
